name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - run: |
        dotnet build TachoClient.sln --configuration Release
        zip -r build-output.zip **/bin/Release/
       
    - name: Upload to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: build-output.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.run_number }}
        draft: false
        prerelease: false
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.2.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY_LOCALIZALIA }}
        host: tacho.fleetmap.pt
        username: servidor
        script: |
          rm -f build-output.zip
          wget -v "https://github.com/fleetmap-io/tacho-client/releases/download/${{ github.run_number }}/build-output.zip"
          unzip -o /home/servidor/build-output.zip
          PID=$(ps -u root | grep TachoClient | grep -v "grep" | awk '{print $1}')
          if [ -n "$PID" ]; then
            echo "Killing process with PID $PID"
            sudo kill -9 $PID
          fi
          sudo nohup ./TachoClient/bin/Release/net8.0/TachoClient &> /dev/null &
    
